parameters:
    _defaults:
        public: true

    coreshop.workflow.manager.history_log_state_identifier: !php/const CoreShop\Bundle\WorkflowBundle\Notes::HISTORY_STATE_LOG

services:
    _defaults:
        public: true

    coreshop.state_machine_manager: '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager'
    CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManagerInterface: '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager'
    CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager:
        arguments:
            - '@workflow.registry'

    coreshop.state_machine_applier: '@CoreShop\Bundle\WorkflowBundle\Applier\StateMachineApplier'
    CoreShop\Bundle\WorkflowBundle\Applier\StateMachineApplier:
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager'

    coreshop.state_machine_cascade_transition: '@CoreShop\Bundle\WorkflowBundle\Callback\CascadeTransition'
    CoreShop\Bundle\WorkflowBundle\Callback\CascadeTransition:
        public: true
        arguments:
            - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager'

    ## event handler
    CoreShop\Bundle\WorkflowBundle\EventListener\WorkflowListener:
        arguments:
            - '%coreshop.state_machine.callbacks%'
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber }


    coreshop.workflow.history_logger: '@CoreShop\Bundle\WorkflowBundle\History\HistoryLoggerInterface'
    CoreShop\Bundle\WorkflowBundle\History\HistoryLoggerInterface: '@CoreShop\Bundle\WorkflowBundle\History\HistoryLogger'
    CoreShop\Bundle\WorkflowBundle\History\HistoryLogger:
        arguments:
            - '@CoreShop\Component\Pimcore\DataObject\NoteService'
            - '@Pimcore\Translation\Translator'
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.workflow.state_history_logger: '@CoreShop\Bundle\WorkflowBundle\History\StateHistoryLoggerInterface'
    CoreShop\Bundle\WorkflowBundle\History\StateHistoryLoggerInterface: '@CoreShop\Bundle\WorkflowBundle\History\StateHistoryLogger'
    CoreShop\Bundle\WorkflowBundle\History\StateHistoryLogger:
        arguments:
            - '@CoreShop\Component\Pimcore\DataObject\NoteService'
            - '@Pimcore\Translation\Translator'
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.repository.workflow_history: '@CoreShop\Bundle\WorkflowBundle\History\HistoryRepositoryInterface'
    CoreShop\Bundle\WorkflowBundle\History\HistoryRepositoryInterface: '@CoreShop\Bundle\WorkflowBundle\History\HistoryRepository'
    CoreShop\Bundle\WorkflowBundle\History\HistoryRepository:
        arguments:
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.workflow.state_info_manager: '@CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManagerInterface'
    CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManagerInterface: '@CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManager'
    CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManager:
        arguments:
            - '@event_dispatcher'
            - '@CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager'
            - '@translator'
            - '@coreshop.repository.workflow_history'
            - '%coreshop.state_machine.colors%'
