parameters:
    _defaults:
        public: true

    coreshop.workflow.manager.history_log_state_identifier: !php/const CoreShop\Bundle\WorkflowBundle\Notes::HISTORY_STATE_LOG

services:
    _defaults:
        public: true

    coreshop.state_machine_manager:
        class: CoreShop\Bundle\WorkflowBundle\Manager\StateMachineManager
        arguments:
            - '@workflow.registry'

    coreshop.state_machine_applier:
        class: CoreShop\Bundle\WorkflowBundle\Applier\StateMachineApplier
        arguments:
            - '@coreshop.state_machine_manager'

    coreshop.state_machine_cascade_transition:
        public: true
        class: CoreShop\Bundle\WorkflowBundle\Callback\CascadeTransition
        arguments:
            - '@coreshop.state_machine_manager'

    ## event handler
    coreshop.state_machine_listener_processor:
        class: CoreShop\Bundle\WorkflowBundle\EventListener\WorkflowListener
        arguments:
            - '%coreshop.state_machine.callbacks%'
            - '@service_container'
        tags:
            - { name: kernel.event_subscriber }

    coreshop.workflow.history_logger:
        class: CoreShop\Bundle\WorkflowBundle\History\HistoryLogger
        arguments:
            - '@coreshop.object_note_service'
            - '@Pimcore\Translation\Translator'
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.workflow.state_history_logger:
        class: CoreShop\Bundle\WorkflowBundle\History\StateHistoryLogger
        arguments:
            - '@coreshop.object_note_service'
            - '@Pimcore\Translation\Translator'
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.repository.workflow_history:
        class: CoreShop\Bundle\WorkflowBundle\History\HistoryRepository
        arguments:
            - '%coreshop.workflow.manager.history_log_state_identifier%'

    coreshop.workflow.state_info_manager:
        class: CoreShop\Bundle\WorkflowBundle\StateManager\WorkflowStateInfoManager
        arguments:
            - '@event_dispatcher'
            - '@coreshop.state_machine_manager'
            - '@translator'
            - '@coreshop.repository.workflow_history'
            - '%coreshop.state_machine.colors%'
